name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
      
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build app
      uses: gradle/gradle-build-action@v2.3.2
      with:
        arguments: assemble
      
    - name: Clean up build artifact
      run: |
        ls build/kotlin
        set -e
        mv app/build/outputs/apk/release/app-release-unsigned.apk EasyStudy.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: EasyStudy
        body: Cringe
        files: |
          EasyStudy.apk
        draft: true
        prerelease: false
